# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
# 必须集成主SDK
pod 'newios_sdk'

# 集成倍业Adapter
pod 'newios_sdk/MercuryAdapter'
pod 'MercurySDK', '4.4.7'

# 集成穿山甲Adapter
pod 'newios_sdk/CSJAdapter'
pod 'Ads-CN-Beta', '6.8.0.1', :subspecs => ['BUAdSDK', 'CSJMediation']

# 集成广点通Adapter
pod 'newios_sdk/GDTAdapter'
pod 'GDTMobSDK', '4.15.30'

# 集成快手Adapter
pod 'newios_sdk/KSAdapter'
pod 'KSAdSDK', '3.3.74'

# 集成百度Adapter
pod 'newios_sdk/BDAdapter'
pod 'BaiduMobAdSDK', '5.373'

# 集成TanxAdapter
pod 'newios_sdk/TanxAdapter'
pod 'TanxSDK', '3.7.2'

# 集成SigMobAdapter
pod 'newios_sdk/SigmobAdapter'
pod 'SigmobAd-iOS', '4.17.0'

# Third
pod 'SDWebImage'
  
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
